apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4cvmfs
  namespace: varnish
  labels:
    k8s-app: v4cvmfs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v4cvmfs
  template:
    metadata:
      labels:
        k8s-app: v4cvmfs
    spec:
      containers:
        - name: v4cvmfs
          image: ivukotic/v4cvmfs
          imagePullPolicy: Always
          env:
            - name: SITE
              value: "<SITENAME>"
            - name: INSTANCE
              value: "<INSTANCE>"
            - name: VARNISH_PORT
              value: "8080"
            - name: VARNISH_MEM
              value: "32G"
            - name: VARNISH_TRANSIENT_MEM
              value: "2G"
          ports:
            - containerPort: 8080
              hostPort: 6081
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/sender.sh
            initialDelaySeconds: 120
            timeoutSeconds: 9
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "1"
              memory: "34Gi"
            limits:
              cpu: "6"
              memory: "48Gi"
      nodeSelector:
        kubernetes.io/hostname: <NODE>
  strategy:
    type: Recreate
