apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4cvmfs
  namespace: v4cvmfs
  labels:
    k8s-app: v4cvmfs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v4cvmfs
  template:
    metadata:
      labels:
        k8s-app: v4cvmfs
    spec:
      containers:
        - name: v4cvmfs
          image: ivukotic/v4cvmfs:latest
          args: ["-t", "3600", "-a", "http=:6081,HTTP"]
          env:
            - name: VARNISH_SIZE
              value: "32G"
            - name: VARNISH_LISTEN_PORT
              value: "6081"
            - name: DAEMON_OPTS
              value: "-a :6081 -T localhost:6082"
          ports:
            - containerPort: 6081
          resources:
            requests:
              cpu: "4"
              memory: "33Gi"
            limits:
              cpu: "48"
              memory: "48Gi"

      hostNetwork: true
      nodeSelector:
        varnish: cvmfs
