apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4cvmfs
  namespace: v4cvmfs
  labels:
    k8s-app: v4cvmfs
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v4cvmfs
  template:
    metadata:
      labels:
        k8s-app: v4cvmfs
    spec:
      containers:
        - name: v4cvmfs
          image: ivukotic/v4cvmfs:latest
          args: ["-t", "3600"]
          env:
            - name: VARNISH_SIZE
              value: "32G"
          ports:
            - containerPort: 80
              hostPort: 6081
          resources:
            requests:
              cpu: "4"
              memory: "33Gi"
            limits:
              cpu: "48"
              memory: "48Gi"

      # hostNetwork: true
      nodeSelector:
        varnish: cvmfs
