# this is to be used on any cluster.
# creates varnish
# use the same pod to try out curls
# curl -XGET "http://localhost/cvmfs/oasis.opensciencegrid.org/.cvmfspublished"
# curl -XGET "http://localhost/cvmfs/desdm.osgstorage.org/.cvmfspublished"
# curl -XGET "http://s1bnl-cvmfs.openhtc.io/cvmfs/desdm.osgstorage.org/.cvmfspublished"
# curl -XGET "http://klei.nikhef.nl:8000/cvmfs/desdm.osgstorage.org/.cvmfspublished"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: v4cvmfs-test
  labels:
    k8s-app: v4cvmfs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: v4cvmfs-test
  template:
    metadata:
      labels:
        k8s-app: v4cvmfs-test
    spec:
      containers:
        - name: v4cvmfs-test
          image: ivukotic/v4cvmfs
          imagePullPolicy: Always
          # args: ["-t", "3600"]
          env:
            - name: SITE
              value: "TEST"
            - name: INSTANCE
              value: "test-01"
            - name: VARNISH_PORT
              value: "8080"
            - name: VARNISH_MEM
              value: "512M"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
