services:
  v4f:
    image: ivukotic/v4cvmfs:cvmfs-no-snmp
    container_name: v4f
    environment:
      SITE: "<SITENAME>"
      INSTANCE: "<INSTANCE>"
      VARNISH_PORT: "8080"
      SNMP_PORT: "3401"
      MONITOR_ES: "true"
      MONITOR_SNMP: "false"
      VARNISH_MEM: "32G"
      VARNISH_TRANSIENT_MEM: "2G"
    ports:
      - "6081:8080"
    volumes:
      - ./vcl/default.vcl:/etc/varnish/default.vcl:ro
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 64G
        reservations:
          cpus: "4.0"
          memory: 4G
    healthcheck:
      test: ["CMD", "/usr/local/bin/sender.sh"]
      interval: 5s
      timeout: 4s
      start_period: 120s
      retries: 3
