services:
  v4f:
    image: ivukotic/v4a
    container_name: v4f
    environment:
      SITE: "<SITENAME>"
      INSTANCE: "<INSTANCE>"
      VARNISH_PORT: "8080"
      VARNISH_MEM: "32G"
      VARNISH_TRANSIENT_MEM: "2G"
    ports:
      - "6082:8080"
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: 64G
        reservations:
          cpus: "2.0"
          memory: 12G
