services:
  v4f:
    image: ivukotic/v4cvmfs
    container_name: v4f
    environment:
      SITE: "<SITENAME>"
      INSTANCE: "<INSTANCE>"
      VARNISH_PORT: "8080"
      VARNISH_MEM: "32G"
      VARNISH_TRANSIENT_MEM: "2G"
    ports:
      - "6081:8080"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 35G
        reservations:
          cpus: "1.0"
          memory: 34G

