name: DockerPush

on:
  push:
    branches:
      - "frontier"
    paths-ignore:
      - "configurations/**"
      - "docker/**"
      - "kube/**"
      - "Manual/**"
      - "testing/**"
      - "README.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set build date
        run: echo "BUILD_DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push Varnish for Conditions Image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ivukotic/v4a:latest,ivukotic/v4a:${{ github.sha }}
          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
