name: Testing all varnishes

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: frontier
          fetch-depth: 0    

      - name: Ensure execute bit
        run: chmod +x ./Monitoring/tester.sh

      - name: Run the script
        run: ./Monitoring/tester.sh
